HH-96771 Update debian/rules

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,25 +1,35 @@
 #!/usr/bin/make -f
-# See debhelper(7) (uncomment to enable)
-# output every command that modifies files on the build system.
-export DH_VERBOSE = 1
-export DH_OPTIONS=-v 
-
-# see FEATURE AREAS in dpkg-buildflags(1)
-#export DEB_BUILD_MAINT_OPTIONS = hardening=+all
-
-# see ENVIRONMENT in dpkg-buildflags(1)
-# package maintainers to append CFLAGS
-#export DEB_CFLAGS_MAINT_APPEND  = -Wall -pedantic
-# package maintainers to append LDFLAGS
-#export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed
-
+export DH_VERBOSE=1
+export DH_OPTIONS=-v
+DEB_BUILD_OPTIONS=nostrip
+SHELL=/bin/bash 
+NGINX_VERSION:= $(shell cat nginx_version)
+NGINX_SRC = $(shell find src/ -mindepth 1 -maxdepth 1 -type d)
+MODULES := nginx_requestid  ngx_brotli testcookie-nginx-module
+INSTALLDIR := $(CURDIR)/debian/nginx-modules//usr/lib/nginx/modules
 
 %:
 	dh $@
 
+override_dh_auto_clean:
+	rm -rf src	
+	git submodule deinit $(MODULES)
 
-# dh_make generated override targets
-# This is example for Cmake (See https://bugs.debian.org/641051 )
-#override_dh_auto_configure:
-#	dh_auto_configure -- #	-DCMAKE_LIBRARY_PATH=$(DEB_HOST_MULTIARCH)
+download_src:
+	mkdir -p src;  cd src;  apt-get source nginx=$(NGINX_VERSION) || echo "Error nginx apt sources not configured. Run \
+        'sudo rsync -Huhvr files/ / && sudo apt-get update'" from project root
 
+override_dh_auto_configure: download_src 
+	git submodule update --init --recursive $(MODULES)
+	cd $(NGINX_SRC); ./configure --with-compat $(addprefix --add-dynamic-module=../../,$(MODULES))
+
+override_dh_auto_build:
+	cd $(NGINX_SRC); make modules
+
+override_dh_auto_install:
+	install -d $(INSTALLDIR)
+	for lib in $(wildcard $(NGINX_SRC)/objs/*.so); do install -D -s $${lib} $(INSTALLDIR); done
+
+override_dh_fixperms:
+	dh_fixperms
+	find debian -name '*.so' -exec chmod 0755 {} +
